# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-VersionedSchema
version:      0.02
version_from: lib/DBIx/VersionedSchema.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      
    Test::TempDatabase:            0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
